package com.deone.extrmtasks.tools;

public class Constants {
    public static final String APP_PREFS = "App_prefs";
    public static final String APP_PREFS_MODE = "App_prefs_mode";
    public static final String APP_PREFS_LANGUE = "App_prefs_langue";
    public static final String APP_PREFS_COUNTRY = "App_prefs_country";
    public static final String APP_PREFS_ADD_TITLE = "App_prefs_add_title";
    public static final String APP_PREFS_ADD_DESCRIPTION = "App_prefs_add_description";
    public static final String TITLE = "title";
    public static final String DESCRIPTION = "description";
    public static final String AVATAR = "avatar";
    public static final String COVER = "cover";
    public static final String APP = "App";
    public static final String CONDITIONS = "Conditions";
    public static final String DATABASE = "Xtasks";
    public static final String TACHES = "Taches";
    public static final String USERS = "Users";
    public static final String COMMENTS = "Comments";
    public static final String TNCOMMENTS = "tncomment";
    public static final String UNCOMMENTS = "uncomments";
    public static final String UCOVER = "ucover";
    public static final String UAVATAR = "uavatar";
    public static final String UNOMS = "unoms";
    public static final String UDESCRIPTION = "udescription";
    public static final String UTELEPHONE = "utelephone";
    public static final String UNTASK = "untask";
    public static final String UID = "uid";
    public static final String TID = "tid";
    public static final String TTITRE = "ttitre";
    public static final String TPAYS = "tpays";
    public static final String TVILLE = "tville";
    public static final String TADRESSE = "tadresse";
    public static final String TCODEPOSTAL = "tcodepostal";
    public static final String TSTATE = "tstate";
    public static final String TLONGITUDE = "tlongitude";
    public static final String TLATITUDE = "tlatitude";
    public static final String TDESCRIPTION = "tdescription";
    public static final String FORMAT_DATE = "EEEE dd MMM yyyy";
    public static final String EN = "en";
    public static final int LOCATION_REQUEST_CODE_ACCESS_COARSE_LOCATION = 101;
    public static final int LOCATION_REQUEST_CODE_ACCESS_FINE_LOCATION = 102;
    public static final int CAMERA_REQUEST_CODE = 200;
    public static final int STORAGE_REQUEST_CODE = 300;
    public static final int MINIMUM_TIME = 10000;
    public static final int MINIMUM_DISTANCE = 50;
}
