package com.deone.extrmtasks.tools;

public class Constants {
    public static final String APP_PREFS = "App_prefs";
    public static final String APP_PREFS_MODE = "App_prefs_mode";
    public static final String APP_PREFS_LANGUE = "App_prefs_langue";
    public static final String APP_PREFS_COUNTRY = "App_prefs_country";
    public static final String APP_PREFS_ADD_TITLE = "App_prefs_add_title";
    public static final String APP_PREFS_ADD_DESCRIPTION = "App_prefs_add_description";
    public static final String APP_PREFS_LOCATION = "App_prefs_location";
    public static final String APP_PREFS_CAMERA = "App_prefs_camera";
    public static final String APP_PREFS_GALLERY = "App_prefs_gallery";
    public static final String APP_PREFS_KEY = "App_prefs_key";
    public static final String APP_PREFS_CURRENT_POSITION = "App_prefs_current_position";
    public static final String APP_PREFS_CURRENT_POSITION_PRIORITY = "App_prefs_current_position_priority";
    public static final String APP_PREFS_LOCALISATION = "App_prefs_localisation";
    public static final String APP_PREFS_CONTACT = "App_prefs_contact";
    public static final String APP_PREFS_STORAGE = "App_prefs_camera";
    public static final String TITLE = "title";
    public static final String DESCRIPTION = "description";
    public static final String AVATAR = "avatar";
    public static final String COVER = "cover";
    public static final String APP = "App";
    public static final String CONDITIONS = "Conditions";
    public static final String DATABASE = "Xtasks";
    public static final String TACHES = "Taches";
    public static final String USERS = "Users";
    public static final String COMMENTS = "Comments";
    public static final String TNCOMMENTS = "tncomment";
    public static final String UNCOMMENTS = "uncomments";
    public static final String UCOVER = "ucover";
    public static final String UAVATAR = "uavatar";
    public static final String UNOMS = "unoms";
    public static final String UDESCRIPTION = "udescription";
    public static final String UTELEPHONE = "utelephone";
    public static final String UNTASK = "untask";
    public static final String IDFRAGMENT = "id_fragment";
    public static final String UID = "uid";
    public static final String TID = "tid";
    public static final String TCOVER = "tcover";
    public static final String TTITRE = "ttitre";
    public static final String TPAYS = "tpays";
    public static final String TVILLE = "tville";
    public static final String TADRESSE = "tadresse";
    public static final String TCODEPOSTAL = "tcodepostal";
    public static final String TSTATE = "tstate";
    public static final String TLONGITUDE = "tlongitude";
    public static final String TLATITUDE = "tlatitude";
    public static final String SIGNALES = "Signales";
    public static final String TDESCRIPTION = "tdescription";
    public static final String FORMAT_DATE = "EEEE dd MMM yyyy";
    public static final String EN = "en";
    public static final String FRAGMENT_ACCOUNT = "account";
    public static final String FRAGMENT_AUTH = "autorisation";
    public static final String FRAGMENT_CONF = "confidentiality";
    public static final String FRAGMENT_GROUP = "group";
    public static final String FRAGMENT_KEY = "key";
    public static final String FRAGMENT_NOT = "notification";
    public static final String FRAGMENT_STOCKAGE = "stockage";
    public static final String KEYS = "Keys";
    public static final String UNKEYS = "unkeys";
    public static final int LOCATION_REQUEST_CODE_ACCESS_COARSE_LOCATION = 101;
    public static final int LOCATION_REQUEST_CODE_ACCESS_FINE_LOCATION = 102;
    public static final int LOCATION_REQUEST_CODE = 100;
    public static final int CAMERA_REQUEST_CODE = 200;
    public static final int STORAGE_REQUEST_CODE = 300;
    public static final int CONTACT_REQUEST_CODE = 400;
    public static final int LOCATION_SERVICE_ID = 175;
    public static final String ACTION_START_LOCATION_SERVICE_ID = "startLocationService";
    public static final String ACTION_STOP_LOCATION_SERVICE_ID = "stopLocationService";
    public static final String LOCATION_SERVICE_SIGNAL_LATITUDE = "location_service_signal_latitude";
    public static final String LOCATION_SERVICE_SIGNAL_LONGITUDE = "location_service_signal_longitude";
    public static final String LOCATION_SERVICE_SIGNAL = "location_service_signal";
    public static final int NOTIFICATION_ID = 007;
    public static final String NOTIFICATION_TAG = "FIREBASEOC";

    public static final String HOME_SERVICE_TAG = "Home service";
    public static final String HOME_SERVICE_TAG_LOCALISATION = "Home service localisation";
    public static final String HOME_SERVICE_TAG_FILTER = "Home service filter";
    public static final String HOME_SERVICE_TAG_LIST = "Home service list";

    // TODO: Test calcul de distance entre deux points

    public static final double r2d = 180.0D / 3.141592653589793D;
    public static final double d2r = 3.141592653589793D / 180.0D;
    public static final double d2km = 111189.57696D * r2d;
}
